### ISSUE TITLE
Error while using $embed

### ISSUE THREAD

**Issue by redsauce117** [Favna/Discord-Self-Bot#6]
![image](https://user-images.githubusercontent.com/24428698/32701509-3e22a83c-c78c-11e7-915e-1ffc2a4a8693.png)

**Comment by redsauce117** [comment]
Also, I set up rich presence just like the instructions instructed, and it doesn't appear to be working, even while looking at my own account with an alt.

**Comment by Favna** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [$embed arg format checking](https://trello.com/c/4ctq1BnT/16-embed-arg-format-checking)

**Comment by Favna** [comment]
This is not an error in the command but rather because the bot takes more than 30 seconds to give the first message (`What should the content be`) which is to fill the args. As the time has then expired it thinks you haven't supplied any args and it errors. There isn't much I can do about that really.

I've experienced this behavior but mostly it would happen just once and then never again. 

That said, if I can work out a good way to first check the format of the arg and whether it matches the required format then i'll add that. Issue added to the trello board

**Comment by Favna** [comment]
As for the RichPresences, can you join my server so I can provide better support from there? https://discord.gg/zdt5yQt
